name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.9'
  SPARK_VERSION: '3.5.0'
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: telestream-insights-hub

jobs:
  # ===================== CODE QUALITY =====================
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - run: |
          pip install --upgrade pip
          pip install flake8 black isort mypy bandit safety

      - run: black --check processing/ api/ tests/
      - run: isort --check-only processing/ api/ tests/
      - run: flake8 processing/ api/ tests/ --max-line-length=120 --extend-ignore=E203,W503
      - run: mypy processing/ api/ --ignore-missing-imports || true
      - run: bandit -r processing/ api/ -ll
      - run: safety check --json

  # ======================= UNIT TESTS ======================
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-asyncio pytest-xdist

      - run: |
          pytest tests/unit/ \
            -v \
            --cov=processing \
            --cov=api \
            --cov-report=xml:coverage.xml \
            --cov-report=term \
            --junit-xml=test-results.xml \
            -n auto

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.python-version }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            test-results.xml
            coverage.xml

  # ==================== INTEGRATION TESTS ==================
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: telestream
          POSTGRES_PASSWORD: telestream123
          POSTGRES_DB: telestream_dw
        ports: [5432:5432]
        options: >-
          --health-cmd pg_isready --health-interval 10s
          --health-timeout 5s --health-retries 5

      redis:
        image: redis:7-alpine
        ports: [6379:6379]
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      - run: |
          PGPASSWORD=telestream123 psql -h localhost -U telestream -d telestream_dw -f tests/fixtures/schema.sql

      - env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: telestream
          DB_PASSWORD: telestream123
          DB_NAME: telestream_dw
          REDIS_URL: redis://localhost:6379
        run: |
          pytest tests/integration/ -v --junit-xml=integration-results.xml

      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: integration-results.xml

  # ==================== DATA QUALITY TESTS =================
  data-quality-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - run: |
          pip install --upgrade pip
          pip install great_expectations pandas pyspark

      - run: |
          python - <<'PY'
          from great_expectations.data_context import DataContext
          ctx = DataContext('./great_expectations')
          result = ctx.run_checkpoint(checkpoint_name='test_checkpoint')
          assert result.success, "Data quality checks failed"
          PY

  # ====================== SECURITY SCAN ====================
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trivy file scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-results.sarif

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Snyk scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  # ====================== BUILD DOCKER =====================
  build-docker:
    runs-on: ubuntu-latest
    needs: [code-quality, unit-tests]
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            SPARK_VERSION=${{ env.SPARK_VERSION }}

  # ======================== NOTIFY ========================
  notify:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow

      - name: Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'CI/CD Pipeline Status: ${{ job.status }}'
          to: data-team@telestream.com
          from: GitHub Actions
          body: |
            Pipeline execution completed with status: ${{ job.status }}
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            View details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
